#pragma once

#define VERSION_MAJOR 0
#define VERSION_MINOR 5
#define VERSION_REVISION 0
#define VERSION_BUILD 0

#define VER_FILE_VERSION       VERSION_MAJOR, VERSION_MINOR, VERSION_REVISION, VERSION_BUILD
#define VER_PRODUCT_VERSION    VER_FILE_VERSION

#define STRINGIZE2(s) #s
#define STRINGIZE(s)  STRINGIZE2(s)

#define VER_FILE_VERSION_STR      STRINGIZE(VERSION_MAJOR) "." STRINGIZE(VERSION_MINOR) "." STRINGIZE(VERSION_REVISION) "." STRINGIZE(VERSION_BUILD)
#define VER_PRODUCT_VERSION_STR   VER_FILE_VERSION_STR
#define VER_COMPANYNAME_STR       ""
#define VER_FILE_DESCRIPTION_STR  "Blockhead Equipment Suffix Overrides"
#define VER_INTERNAL_NAME_STR     "BlockheadEquipSuffix"
#define VER_COPYRIGHT_STR         ""
#define VER_ORIGINAL_FILENAME_STR "BlockheadEquipSuffix.dll"
#define VER_PRODUCTNAME_STR       "BlockheadEquipSuffix"
